apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: superset
      context: .
      custom:
        buildCommand: .staroid/build.sh
deploy:
  statusCheckDeadlineSeconds: 600
  kubectl:
    manifests:
      - k8s/env.yaml
      - k8s/redis.yaml
      - k8s/postgres.yaml
      - k8s/superset.yaml
profiles:
  - name: minikube
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: k8s/minikube.yaml
